#!/usr/bin/env python3
"""
Build the unstructured Euler mesh around a NACA 0012 airfoil used by
inv_NACA0012.cfg (SU2 8.3).

    python3 makeMesh.py          # writes naca0012.geo, runs gmsh, writes .su2

Requires gmsh (https://gmsh.info, GPLv2) on the PATH. The resulting mesh is a
triangular O-domain: the airfoil (unit chord, sharp trailing edge) sits at the
centre of a circular farfield 100 chords away, with the cell size graded from
the airfoil surface to the outer boundary.

Boundary markers written in the .su2 file:
    airfoil    the profile surface  (Euler slip wall)
    farfield   the outer circle     (characteristic-based farfield)
"""

import math
import subprocess
import sys

GEO = "naca0012.geo"
MSH = "naca0012.msh"
SU2 = "mesh_NACA0012_inv.su2"

N_AIRFOIL = 160        # points per side of the profile
R_FAR = 100.0          # farfield radius, in chords
H_LE = 0.0015          # target cell size at the leading/trailing edge
H_AIRFOIL = 0.006      # target cell size along the rest of the profile
H_FAR = 15.0           # target cell size on the outer boundary


def naca0012(x):
    """Half-thickness of a sharp-trailing-edge NACA 0012 at chord station x."""
    return 0.6 * (0.2969 * math.sqrt(x)
                  - 0.1260 * x
                  - 0.3516 * x ** 2
                  + 0.2843 * x ** 3
                  - 0.1036 * x ** 4)


def write_geo(path):
    # cosine spacing clusters points at the leading and trailing edges
    xs = [0.5 * (1.0 - math.cos(math.pi * i / (N_AIRFOIL - 1)))
          for i in range(N_AIRFOIL)]

    lines = ["// NACA 0012 Euler mesh - generated by makeMesh.py",
             "SetFactory(\"OpenCASCADE\");", ""]

    def size_at(x):
        # finer near the two edges, coarser over the mid chord
        edge = min(x, 1.0 - x)
        return H_LE + (H_AIRFOIL - H_LE) * min(1.0, edge / 0.15)

    pid = 0
    upper, lower = [], []

    # upper surface, leading edge -> trailing edge
    for x in xs:
        pid += 1
        lines.append("Point(%d) = {%.10f, %.10f, 0, %.6f};"
                     % (pid, x, naca0012(x), size_at(x)))
        upper.append(pid)

    # lower surface, trailing edge -> leading edge (endpoints already exist)
    for x in reversed(xs[1:-1]):
        pid += 1
        lines.append("Point(%d) = {%.10f, %.10f, 0, %.6f};"
                     % (pid, x, -naca0012(x), size_at(x)))
        lower.append(pid)

    loop = upper + lower
    lines.append("")
    lines.append("Spline(1) = {%s};" % ", ".join(str(p) for p in loop + [loop[0]]))
    lines.append("Curve Loop(1) = {1};")
    lines.append("")

    # circular farfield centred on the quarter chord
    lines.append("Point(1000) = {0.25, 0, 0, %.6f};" % H_FAR)
    lines.append("Point(1001) = {%.6f, 0, 0, %.6f};" % (0.25 + R_FAR, H_FAR))
    lines.append("Point(1002) = {0.25, %.6f, 0, %.6f};" % (R_FAR, H_FAR))
    lines.append("Point(1003) = {%.6f, 0, 0, %.6f};" % (0.25 - R_FAR, H_FAR))
    lines.append("Point(1004) = {0.25, %.6f, 0, %.6f};" % (-R_FAR, H_FAR))
    lines.append("Circle(2) = {1001, 1000, 1002};")
    lines.append("Circle(3) = {1002, 1000, 1003};")
    lines.append("Circle(4) = {1003, 1000, 1004};")
    lines.append("Circle(5) = {1004, 1000, 1001};")
    lines.append("Curve Loop(2) = {2, 3, 4, 5};")
    lines.append("")
    lines.append("Plane Surface(1) = {2, 1};")
    lines.append("")
    lines.append("Physical Curve(\"airfoil\") = {1};")
    lines.append("Physical Curve(\"farfield\") = {2, 3, 4, 5};")
    lines.append("Physical Surface(\"fluid\") = {1};")
    lines.append("")
    lines.append("Mesh.MshFileVersion = 2.2;")
    lines.append("Mesh.Algorithm = 5;   // Delaunay")

    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")


def read_msh22(path):
    """Minimal reader for the ASCII gmsh 2.2 format."""
    with open(path) as fh:
        tokens = fh.read().split("\n")

    nodes, elements, names = {}, [], {}
    i = 0
    while i < len(tokens):
        tag = tokens[i].strip()
        if tag == "$PhysicalNames":
            n = int(tokens[i + 1])
            for j in range(n):
                dim, num, name = tokens[i + 2 + j].split(None, 2)
                names[int(num)] = name.strip().strip('"')
            i += 2 + n
        elif tag == "$Nodes":
            n = int(tokens[i + 1])
            for j in range(n):
                parts = tokens[i + 2 + j].split()
                nodes[int(parts[0])] = (float(parts[1]), float(parts[2]))
            i += 2 + n
        elif tag == "$Elements":
            n = int(tokens[i + 1])
            for j in range(n):
                parts = [int(p) for p in tokens[i + 2 + j].split()]
                etype, ntags = parts[1], parts[2]
                physical = parts[3] if ntags >= 1 else 0
                elements.append((etype, physical, parts[3 + ntags:]))
            i += 2 + n
        else:
            i += 1

    return nodes, elements, names


def write_su2(path, nodes, elements, names):
    # renumber the gmsh node ids to a dense 0-based numbering
    ids = sorted(nodes)
    remap = {old: new for new, old in enumerate(ids)}

    tris = [e for e in elements if e[0] == 2]
    lines_ = [e for e in elements if e[0] == 1]

    def area(n):
        (x1, y1), (x2, y2), (x3, y3) = (nodes[n[0]], nodes[n[1]], nodes[n[2]])
        return 0.5 * ((x2 - x1) * (y3 - y1) - (x3 - x1) * (y2 - y1))

    with open(path, "w") as fh:
        fh.write("NDIME= 2\n")
        fh.write("NELEM= %d\n" % len(tris))
        for k, (_, _, n) in enumerate(tris):
            # SU2 expects counter-clockwise triangles
            if area(n) < 0:
                n = [n[0], n[2], n[1]]
            fh.write("5 %d %d %d %d\n"
                     % (remap[n[0]], remap[n[1]], remap[n[2]], k))

        fh.write("NPOIN= %d\n" % len(ids))
        for old in ids:
            x, y = nodes[old]
            fh.write("%.12f %.12f %d\n" % (x, y, remap[old]))

        groups = {}
        for _, physical, n in lines_:
            groups.setdefault(names.get(physical, str(physical)), []).append(n)

        fh.write("NMARK= %d\n" % len(groups))
        for tag in sorted(groups):
            fh.write("MARKER_TAG= %s\n" % tag)
            fh.write("MARKER_ELEMS= %d\n" % len(groups[tag]))
            for n in groups[tag]:
                fh.write("3 %d %d\n" % (remap[n[0]], remap[n[1]]))

    return len(tris), len(ids), {k: len(v) for k, v in groups.items()}


def main():
    write_geo(GEO)
    subprocess.run(["gmsh", "-2", GEO, "-o", MSH, "-format", "msh22"],
                   check=True, stdout=subprocess.DEVNULL)
    nodes, elements, names = read_msh22(MSH)
    ntri, npoin, markers = write_su2(SU2, nodes, elements, names)
    print("%s: %d triangles, %d points, markers %s"
          % (SU2, ntri, npoin, markers), file=sys.stderr)


if __name__ == "__main__":
    main()
