#!/usr/bin/env python3
"""
Generate the structured hexahedral mesh of the cantilever beam used by
beam.inp (CalculiX 2.21).

    python3 makeMesh.py > mesh.inp

Geometry: L x B x H = 1.0 x 0.05 x 0.05 m, discretised with NX x NY x NZ
linear brick (C3D8) elements. Node and element sets written:

    Nall      all nodes                Eall     all elements
    FIXED     nodes on x = 0           TIPLOAD  nodes on x = L
"""

import sys

L, B, H = 1.0, 0.05, 0.05
NX, NY, NZ = 80, 8, 8


def nid(i, j, k):
    """1-based node id of the grid point (i, j, k)."""
    return 1 + i * (NY + 1) * (NZ + 1) + j * (NZ + 1) + k


def main(out=sys.stdout):
    out.write("** Cantilever beam mesh - generated by makeMesh.py\n")
    out.write("** %g x %g x %g m, %d x %d x %d C3D8 elements\n"
              % (L, B, H, NX, NY, NZ))

    out.write("*NODE, NSET=Nall\n")
    for i in range(NX + 1):
        for j in range(NY + 1):
            for k in range(NZ + 1):
                out.write("%d, %.8f, %.8f, %.8f\n"
                          % (nid(i, j, k), i * L / NX, j * B / NY, k * H / NZ))

    out.write("*ELEMENT, TYPE=C3D8, ELSET=Eall\n")
    eid = 0
    for i in range(NX):
        for j in range(NY):
            for k in range(NZ):
                eid += 1
                # CalculiX C3D8 connectivity: bottom face then top face,
                # both counter-clockwise seen from outside
                n = [nid(i,     j,     k),
                     nid(i + 1, j,     k),
                     nid(i + 1, j + 1, k),
                     nid(i,     j + 1, k),
                     nid(i,     j,     k + 1),
                     nid(i + 1, j,     k + 1),
                     nid(i + 1, j + 1, k + 1),
                     nid(i,     j + 1, k + 1)]
                out.write("%d, %s\n" % (eid, ", ".join(str(x) for x in n)))

    def write_nset(name, ids):
        out.write("*NSET, NSET=%s\n" % name)
        for c in range(0, len(ids), 8):
            out.write(", ".join(str(x) for x in ids[c:c + 8]) + ",\n")

    write_nset("FIXED",
               [nid(0, j, k) for j in range(NY + 1) for k in range(NZ + 1)])
    write_nset("TIPLOAD",
               [nid(NX, j, k) for j in range(NY + 1) for k in range(NZ + 1)])


if __name__ == "__main__":
    main()
